name: release-test

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      # setup
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: install expect
        run: sudo apt install expect

      # build resources
      - run: node ./dev/icon_generator/makeicons
      - run: node ./dev/resource_packager

      # build docs
      - run: npm ci
        working-directory: docs
      - run: npm run build
        working-directory: docs

      # publish
      # - name: get version
      #   id: version
      #   uses: martinbeentjes/npm-get-version-action@v1.2.3
      # - name: publish to itch.io
      #   uses: josephbmanley/butler-publish-itchio-action@v1.0.3
      #   env:
      #     BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
      #     CHANNEL: win-linux-mac-stable
      #     ITCH_GAME: bitsy
      #     ITCH_USER: ledoux
      #     PACKAGE: editor
      #     VERSION: ${{ steps.version.outputs.current-version }}

      - name: list files to help debug upload
        run: find . | grep -v "node_modules" | grep -v "git"
      - name: publish to bitsy.org (under /release-test)
        run: expect -c 'spawn sftp ${{ secrets.FTP_USER }}@${{ secrets.FTP_SERVER }} ; sleep 10 ; send "yes\r" ; expect "password:" ; send "${{ secrets.FTP_PASS }}\r" ; expect "sftp>" ; mkdir release-test; send "put -r release-test/\r" ; expect "sftp>" ; send "bye\r" ; expect eof'
